# Generated by Django 3.2.8 on 2021-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cap_created_cap_updated_alter_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='cap',
            name='imege',
            field=models.ImageField(blank=True, null=True, upload_to='caps'),
        ),
    ]
