# Generated by Django 4.0 on 2021-12-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211229_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.brand')),
                ('caps', models.ManyToManyField(to='main.Cap')),
            ],
            bases=('main.brand', models.Model),
        ),
    ]
